const EXCEPTION = "EXCEPTION";
const CLEAR_EXCEPTION_MSG = "CLEAR_EXCEPTION_MSG";
const SET_USER_ID = "SET_USER_ID";
const CLEAR_USER_ID = "CLEAR_USER_ID";
const SET_MENU_TOPIC = "SET_MENU_TOPIC";
const CLEAR_MENU_TOPIC = "CLEAR_MENU_TOPIC";
const SET_ALL_TOPICS = "SET_ALL_TOPICS";

const Types = {
	exception: {
		EXCEPTION,
		CLEAR_EXCEPTION_MSG,
	},
	user: {
		SET_USER_ID,
		CLEAR_USER_ID,
	},
	topic: {
		SET_MENU_TOPIC,
		CLEAR_MENU_TOPIC,
		SET_ALL_TOPICS,
	},
};

export default Types;
