const EXCEPTION = "EXCEPTION";
const CLEAR_EXCEPTION_MSG = "CLEAR_EXCEPTION_MSG";
const SET_USER = "SET_USER";
const CLEAR_USER = "CLEAR_USER";
const SET_MENU_TOPIC = "SET_MENU_TOPIC";
const CLEAR_MENU_TOPIC = "CLEAR_MENU_TOPIC";
const SET_ALL_TOPICS = "SET_ALL_TOPICS";
const SET_ALL_BRANDS = "SET_ALL_BRANDS";
const SET_SELECTED_BRANDS = "SET_SELECTED_BRANDS";
const CLEAR_SELECTED_BRANDS = "CLEAR_SELECTED_BRANDS";
const SET_MY_TROVE = "SET_MY_TROVE";
const CLEAR_MY_TROVE = "CLEAR_MY_TROVE";

const Types = {
	exception: {
		EXCEPTION,
		CLEAR_EXCEPTION_MSG,
	},
	user: {
		SET_USER,
		CLEAR_USER,
	},
	topic: {
		SET_MENU_TOPIC,
		CLEAR_MENU_TOPIC,
		SET_ALL_TOPICS,
	},
	brands: {
		SET_ALL_BRANDS,
		SET_SELECTED_BRANDS,
		CLEAR_SELECTED_BRANDS,
	},
	myTrove: {
		SET_MY_TROVE,
		CLEAR_MY_TROVE,
	},
};

export default Types;
