export const Images = {
	play: "playCircle",
	heart: "smallHeart",
	share: "share",
	search: "search",
	grid: "grid",
	selectedBookmark: "filledBookmark",
	edit: "edit",
	menu: "bergur",
	home: "home",
	back: "arrowLeft",
	podcast: "headphones",
	twitter: "twitter",
	facebook: "facebook",
	aA: "aA",
	book: "book",
	googlePlus: "googlePlus",
	loginButton: require("./login_button.png"),
	subscribeButton: require("./subscribe.png"),
	downloadButton: require("./downloadButton.png"),
	mailBox: require("./mailBox.png"),
};
